# Different ways of creating NumPy arrays:

In [6]:
import numpy as np

In [8]:
var_1=np.array([1,2,3,4]) #ID

In [10]:
print(var_1)

[1 2 3 4]


In [12]:
var_2=np.array([[1,2,3],[4,5,6]])

In [14]:
print(var_2)

[[1 2 3]
 [4 5 6]]


In [18]:
#array of zero:
z=np.zeros((3,3),dtype="int")
z

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [28]:
#array of random elements:
np.random.seed(4)
random=np.random.rand(4,4)
random

array([[0.96702984, 0.54723225, 0.97268436, 0.71481599],
       [0.69772882, 0.2160895 , 0.97627445, 0.00623026],
       [0.25298236, 0.43479153, 0.77938292, 0.19768507],
       [0.86299324, 0.98340068, 0.16384224, 0.59733394]])

In [32]:
np.random.seed(4)
np.random.randn(4,4)

array([[ 0.05056171,  0.49995133, -0.99590893,  0.69359851],
       [-0.41830152, -1.58457724, -0.64770677,  0.59857517],
       [ 0.33225003, -1.14747663,  0.61866969, -0.08798693],
       [ 0.4250724 ,  0.33225315, -1.15681626,  0.35099715]])

In [43]:
np.random.seed(4)
x_1=np.random.randint(low=50,high=100,size=(4,4))

# Slicing and indexing:

In [45]:
x_1

array([[96, 55, 51, 90],
       [73, 58, 59, 89],
       [95, 80, 90, 86],
       [94, 88, 92, 53]])

In [47]:
x_1[1,1]

58

In [49]:
x_1[3,0]

94

In [53]:
x_1[0:2,0:2]

array([[96, 55],
       [73, 58]])

In [55]:
x_1[2:3,2:]

array([[90, 86]])

#Manipulation of array:

In [60]:
#Creation of identity matrix:
np.identity(3,dtype="int")

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [68]:
b=np.arange(1,13).reshape(3,4)

In [70]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [72]:
b=b.ravel()

In [74]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [76]:
c=np.arange(1,13).reshape(4,3)
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [78]:
c.transpose()

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

#Stacking and Splitting of a matrix

In [81]:
mat_1=np.arange(12).reshape(3,4)
mat_2=np.arange(12,24).reshape(3,4)

In [83]:
mat_1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [85]:
mat_2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [93]:
v=np.vstack((mat_1,mat_2))
v

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [91]:
h=np.hstack((mat_1,mat_2))
h

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [95]:
np.hsplit(v,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13],
        [16, 17],
        [20, 21]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15],
        [18, 19],
        [22, 23]])]

In [99]:
np.vsplit(h,3)

[array([[ 0,  1,  2,  3, 12, 13, 14, 15]]),
 array([[ 4,  5,  6,  7, 16, 17, 18, 19]]),
 array([[ 8,  9, 10, 11, 20, 21, 22, 23]])]

In [2]:
# Different ways of creating Numpy arrays:

In [4]:
import numpy as np

In [6]:
var_1=np.array([1,2,3,4]) #1D

In [8]:
print(var_1)

[1 2 3 4]


In [10]:
var_2=np.array([[1,2,3],[4,5,6]])

In [12]:
print(var_2)

[[1 2 3]
 [4 5 6]]


In [14]:
#array of zero:
z=np.zeros((3,3),dtype="int")
z

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [16]:
#array of ones:
x=np.ones((4,4),dtype="int")
x

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [18]:
#array of random elements:
np.random.seed(4)
random=np.random.rand(4,4)
random

array([[0.96702984, 0.54723225, 0.97268436, 0.71481599],
       [0.69772882, 0.2160895 , 0.97627445, 0.00623026],
       [0.25298236, 0.43479153, 0.77938292, 0.19768507],
       [0.86299324, 0.98340068, 0.16384224, 0.59733394]])

In [20]:
np.random.seed(4)
np.random.randn(4,4)

array([[ 0.05056171,  0.49995133, -0.99590893,  0.69359851],
       [-0.41830152, -1.58457724, -0.64770677,  0.59857517],
       [ 0.33225003, -1.14747663,  0.61866969, -0.08798693],
       [ 0.4250724 ,  0.33225315, -1.15681626,  0.35099715]])

In [22]:
x_1=np.random.randint(high=100,low=50,size=(4,4))

#Slicing and indexing

In [25]:
x_1

array([[65, 84, 81, 67],
       [98, 67, 75, 59],
       [98, 62, 73, 80],
       [72, 53, 61, 73]])

In [27]:
x_1[1,1]

67

In [29]:
x_1[3,0]

72

In [31]:
x_1[0:2,0:2]

array([[65, 84],
       [98, 67]])

In [33]:
x_1[2:3,2:]

array([[73, 80]])

#Manipulation of array:

In [38]:
#creation of identity matrix:
np.identity(3,dtype="int")

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [42]:
b=np.arange(1,13).reshape(3,4)

In [44]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [48]:
b=b.ravel()

In [50]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [52]:
c=np.arange(1,13).reshape(4,3)
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [56]:
c.transpose()

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

Stacking and Splitting of a matrix:

In [59]:
mat_1=np.arange(12).reshape(3,4)
mat_2=np.arange(12,24).reshape(3,4)

In [61]:
mat_1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [63]:
mat_2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [75]:
v=np.vstack((mat_1,mat_2))
v

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [71]:
h=np.hstack((mat_1,mat_2))
h

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [77]:
np.hsplit(v,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13],
        [16, 17],
        [20, 21]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15],
        [18, 19],
        [22, 23]])]