In [ ]:
NumPy--->Numerical Python 

----->Array--> An array is the ordered data structure that contains data of similar type.


In [5]:
import numpy as np

In [7]:
array_1=np.array([1,2,3])
print(array_1)

[1 2 3]


In [9]:
array_2=np.array((30,40,50))
print(array_2)

[30 40 50]


In [13]:
ARRAY_3=np.array([[1,2,3],[4,5,6],[5,6,7]])
print(ARRAY_3)

[[1 2 3]
 [4 5 6]
 [5 6 7]]


In [15]:
np.array([1,2,3,4],dtype="complex")

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [17]:
np.array([1,2,3,4],dtype="float")

array([1., 2., 3., 4.])

In [19]:
list_1=[10,20,30]
print(list_1)

[10, 20, 30]


# what is the major difference between numpy array and the python lists:


In [22]:
array_1

array([1, 2, 3])

In [24]:
array_2


array([30, 40, 50])

In [26]:
print (array_1+array_2)

[31 42 53]


In [30]:
list_1=[1,2,3]
list_2=[30,40,50]
print(list_1+list_2)

[1, 2, 3, 30, 40, 50]


In [32]:
list_ans=[]
for i,j in zip(list_1,list_2):

  list_ans.append(i+j)
print(list_ans)

[31, 42, 53]


In [ ]:
--->NumPy arrays have fixed size of array creation but it is not the case when we talk above lists.
--->The elements in the numpy array are all required to be of same data type.
---->NumPy takes very less time to perform arithmetic activites between arrays where lists they take time.
----> NumPy array takes less space as compared to that of lists.

In [34]:
#how to check the dimension of the array:
array_1.ndim

1

In [36]:
ARRAY_3.ndim

2

In [38]:
#how we can check the shape of the matrix:
array_1.shape

(3,)

In [40]:
ARRAY_3.shape

(3, 3)

In [42]:
#how can we check the size of the array:
ARRAY_3.size

9

In [44]:
array_1.size

3

Array Attributes:

In [75]:
a1=np.arange(10).reshape(5,2) #arrange helps us to create create same as that of the range function
                #but in ID format
print(a1)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [71]:
a2=np.arange(12,dtype="float").reshape(4,3)

In [73]:
print(a2)

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


In [61]:
12*1
6*2
2*6
1*12
3*4
4*3

12

In [81]:
a2=a2.astype(np.int64)  #changing the dtype of the array

In [85]:
a2*4

array([[ 0,  4,  8],
       [12, 16, 20],
       [24, 28, 32],
       [36, 40, 44]], dtype=int64)

In [87]:
for i in a2:
    print(i)

[0 1 2]
[3 4 5]
[6 7 8]
[ 9 10 11]


In [89]:
for i in np.nditer(a2):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [91]:
a2>5

array([[False, False, False],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])